// Code generated by protoc-gen-go. DO NOT EDIT.
// source: broker.proto

package protocol

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_UNKNOWN_MESSAGE_TYPE MessageType = 0
	MessageType_WELCOME              MessageType = 1
	MessageType_CONNECT              MessageType = 2
	MessageType_WEBRTC_OFFER         MessageType = 3
	MessageType_WEBRTC_ANSWER        MessageType = 4
	MessageType_WEBRTC_ICE_CANDIDATE MessageType = 5
	MessageType_PING                 MessageType = 6
	MessageType_SUBSCRIPTION         MessageType = 7
	MessageType_AUTH                 MessageType = 8
	MessageType_TOPIC                MessageType = 9
	MessageType_TOPIC_FW             MessageType = 10
	MessageType_TOPIC_IDENTITY       MessageType = 11
	MessageType_TOPIC_IDENTITY_FW    MessageType = 12
)

var MessageType_name = map[int32]string{
	0:  "UNKNOWN_MESSAGE_TYPE",
	1:  "WELCOME",
	2:  "CONNECT",
	3:  "WEBRTC_OFFER",
	4:  "WEBRTC_ANSWER",
	5:  "WEBRTC_ICE_CANDIDATE",
	6:  "PING",
	7:  "SUBSCRIPTION",
	8:  "AUTH",
	9:  "TOPIC",
	10: "TOPIC_FW",
	11: "TOPIC_IDENTITY",
	12: "TOPIC_IDENTITY_FW",
}

var MessageType_value = map[string]int32{
	"UNKNOWN_MESSAGE_TYPE": 0,
	"WELCOME":              1,
	"CONNECT":              2,
	"WEBRTC_OFFER":         3,
	"WEBRTC_ANSWER":        4,
	"WEBRTC_ICE_CANDIDATE": 5,
	"PING":                 6,
	"SUBSCRIPTION":         7,
	"AUTH":                 8,
	"TOPIC":                9,
	"TOPIC_FW":             10,
	"TOPIC_IDENTITY":       11,
	"TOPIC_IDENTITY_FW":    12,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{0}
}

type Role int32

const (
	Role_UNKNOWN_ROLE         Role = 0
	Role_CLIENT               Role = 1
	Role_COMMUNICATION_SERVER Role = 2
)

var Role_name = map[int32]string{
	0: "UNKNOWN_ROLE",
	1: "CLIENT",
	2: "COMMUNICATION_SERVER",
}

var Role_value = map[string]int32{
	"UNKNOWN_ROLE":         0,
	"CLIENT":               1,
	"COMMUNICATION_SERVER": 2,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{1}
}

type Format int32

const (
	Format_UNKNOWN_FORMAT Format = 0
	Format_PLAIN          Format = 1
	Format_GZIP           Format = 2
)

var Format_name = map[int32]string{
	0: "UNKNOWN_FORMAT",
	1: "PLAIN",
	2: "GZIP",
}

var Format_value = map[string]int32{
	"UNKNOWN_FORMAT": 0,
	"PLAIN":          1,
	"GZIP":           2,
}

func (x Format) String() string {
	return proto.EnumName(Format_name, int32(x))
}

func (Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{2}
}

type CoordinatorMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CoordinatorMessage) Reset()         { *m = CoordinatorMessage{} }
func (m *CoordinatorMessage) String() string { return proto.CompactTextString(m) }
func (*CoordinatorMessage) ProtoMessage()    {}
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{0}
}

func (m *CoordinatorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoordinatorMessage.Unmarshal(m, b)
}
func (m *CoordinatorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoordinatorMessage.Marshal(b, m, deterministic)
}
func (m *CoordinatorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoordinatorMessage.Merge(m, src)
}
func (m *CoordinatorMessage) XXX_Size() int {
	return xxx_messageInfo_CoordinatorMessage.Size(m)
}
func (m *CoordinatorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CoordinatorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CoordinatorMessage proto.InternalMessageInfo

func (m *CoordinatorMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

type WelcomeMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	Alias                uint64      `protobuf:"varint,2,opt,name=alias,proto3" json:"alias,omitempty"`
	AvailableServers     []uint64    `protobuf:"varint,3,rep,packed,name=available_servers,json=availableServers,proto3" json:"available_servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WelcomeMessage) Reset()         { *m = WelcomeMessage{} }
func (m *WelcomeMessage) String() string { return proto.CompactTextString(m) }
func (*WelcomeMessage) ProtoMessage()    {}
func (*WelcomeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{1}
}

func (m *WelcomeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WelcomeMessage.Unmarshal(m, b)
}
func (m *WelcomeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WelcomeMessage.Marshal(b, m, deterministic)
}
func (m *WelcomeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WelcomeMessage.Merge(m, src)
}
func (m *WelcomeMessage) XXX_Size() int {
	return xxx_messageInfo_WelcomeMessage.Size(m)
}
func (m *WelcomeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WelcomeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WelcomeMessage proto.InternalMessageInfo

func (m *WelcomeMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *WelcomeMessage) GetAlias() uint64 {
	if m != nil {
		return m.Alias
	}
	return 0
}

func (m *WelcomeMessage) GetAvailableServers() []uint64 {
	if m != nil {
		return m.AvailableServers
	}
	return nil
}

type ConnectMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	FromAlias            uint64      `protobuf:"varint,2,opt,name=from_alias,json=fromAlias,proto3" json:"from_alias,omitempty"`
	ToAlias              uint64      `protobuf:"varint,3,opt,name=to_alias,json=toAlias,proto3" json:"to_alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConnectMessage) Reset()         { *m = ConnectMessage{} }
func (m *ConnectMessage) String() string { return proto.CompactTextString(m) }
func (*ConnectMessage) ProtoMessage()    {}
func (*ConnectMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{2}
}

func (m *ConnectMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectMessage.Unmarshal(m, b)
}
func (m *ConnectMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectMessage.Marshal(b, m, deterministic)
}
func (m *ConnectMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectMessage.Merge(m, src)
}
func (m *ConnectMessage) XXX_Size() int {
	return xxx_messageInfo_ConnectMessage.Size(m)
}
func (m *ConnectMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectMessage proto.InternalMessageInfo

func (m *ConnectMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *ConnectMessage) GetFromAlias() uint64 {
	if m != nil {
		return m.FromAlias
	}
	return 0
}

func (m *ConnectMessage) GetToAlias() uint64 {
	if m != nil {
		return m.ToAlias
	}
	return 0
}

type WebRtcMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	FromAlias            uint64      `protobuf:"varint,2,opt,name=from_alias,json=fromAlias,proto3" json:"from_alias,omitempty"`
	ToAlias              uint64      `protobuf:"varint,3,opt,name=to_alias,json=toAlias,proto3" json:"to_alias,omitempty"`
	Sdp                  string      `protobuf:"bytes,4,opt,name=sdp,proto3" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WebRtcMessage) Reset()         { *m = WebRtcMessage{} }
func (m *WebRtcMessage) String() string { return proto.CompactTextString(m) }
func (*WebRtcMessage) ProtoMessage()    {}
func (*WebRtcMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{3}
}

func (m *WebRtcMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebRtcMessage.Unmarshal(m, b)
}
func (m *WebRtcMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebRtcMessage.Marshal(b, m, deterministic)
}
func (m *WebRtcMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebRtcMessage.Merge(m, src)
}
func (m *WebRtcMessage) XXX_Size() int {
	return xxx_messageInfo_WebRtcMessage.Size(m)
}
func (m *WebRtcMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WebRtcMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WebRtcMessage proto.InternalMessageInfo

func (m *WebRtcMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *WebRtcMessage) GetFromAlias() uint64 {
	if m != nil {
		return m.FromAlias
	}
	return 0
}

func (m *WebRtcMessage) GetToAlias() uint64 {
	if m != nil {
		return m.ToAlias
	}
	return 0
}

func (m *WebRtcMessage) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

type MessageHeader struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MessageHeader) Reset()         { *m = MessageHeader{} }
func (m *MessageHeader) String() string { return proto.CompactTextString(m) }
func (*MessageHeader) ProtoMessage()    {}
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{4}
}

func (m *MessageHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageHeader.Unmarshal(m, b)
}
func (m *MessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageHeader.Marshal(b, m, deterministic)
}
func (m *MessageHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageHeader.Merge(m, src)
}
func (m *MessageHeader) XXX_Size() int {
	return xxx_messageInfo_MessageHeader.Size(m)
}
func (m *MessageHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MessageHeader proto.InternalMessageInfo

func (m *MessageHeader) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

type PingMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	Time                 float64     `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{5}
}

func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (m *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(m, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *PingMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// NOTE: topics is a space separated string in the format specified by Format
type SubscriptionMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	Format               Format      `protobuf:"varint,2,opt,name=format,proto3,enum=protocol.Format" json:"format,omitempty"`
	Topics               []byte      `protobuf:"bytes,3,opt,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SubscriptionMessage) Reset()         { *m = SubscriptionMessage{} }
func (m *SubscriptionMessage) String() string { return proto.CompactTextString(m) }
func (*SubscriptionMessage) ProtoMessage()    {}
func (*SubscriptionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{6}
}

func (m *SubscriptionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscriptionMessage.Unmarshal(m, b)
}
func (m *SubscriptionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscriptionMessage.Marshal(b, m, deterministic)
}
func (m *SubscriptionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionMessage.Merge(m, src)
}
func (m *SubscriptionMessage) XXX_Size() int {
	return xxx_messageInfo_SubscriptionMessage.Size(m)
}
func (m *SubscriptionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionMessage proto.InternalMessageInfo

func (m *SubscriptionMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *SubscriptionMessage) GetFormat() Format {
	if m != nil {
		return m.Format
	}
	return Format_UNKNOWN_FORMAT
}

func (m *SubscriptionMessage) GetTopics() []byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

type AuthMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	Role                 Role        `protobuf:"varint,2,opt,name=role,proto3,enum=protocol.Role" json:"role,omitempty"`
	Body                 []byte      `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AuthMessage) Reset()         { *m = AuthMessage{} }
func (m *AuthMessage) String() string { return proto.CompactTextString(m) }
func (*AuthMessage) ProtoMessage()    {}
func (*AuthMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{7}
}

func (m *AuthMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMessage.Unmarshal(m, b)
}
func (m *AuthMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMessage.Marshal(b, m, deterministic)
}
func (m *AuthMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMessage.Merge(m, src)
}
func (m *AuthMessage) XXX_Size() int {
	return xxx_messageInfo_AuthMessage.Size(m)
}
func (m *AuthMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMessage proto.InternalMessageInfo

func (m *AuthMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *AuthMessage) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_UNKNOWN_ROLE
}

func (m *AuthMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type TopicMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	FromAlias            uint64      `protobuf:"varint,2,opt,name=from_alias,json=fromAlias,proto3" json:"from_alias,omitempty"`
	Topic                string      `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Body                 []byte      `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TopicMessage) Reset()         { *m = TopicMessage{} }
func (m *TopicMessage) String() string { return proto.CompactTextString(m) }
func (*TopicMessage) ProtoMessage()    {}
func (*TopicMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{8}
}

func (m *TopicMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicMessage.Unmarshal(m, b)
}
func (m *TopicMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicMessage.Marshal(b, m, deterministic)
}
func (m *TopicMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicMessage.Merge(m, src)
}
func (m *TopicMessage) XXX_Size() int {
	return xxx_messageInfo_TopicMessage.Size(m)
}
func (m *TopicMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TopicMessage proto.InternalMessageInfo

func (m *TopicMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *TopicMessage) GetFromAlias() uint64 {
	if m != nil {
		return m.FromAlias
	}
	return 0
}

func (m *TopicMessage) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *TopicMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type TopicFWMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	FromAlias            uint64      `protobuf:"varint,2,opt,name=from_alias,json=fromAlias,proto3" json:"from_alias,omitempty"`
	Body                 []byte      `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TopicFWMessage) Reset()         { *m = TopicFWMessage{} }
func (m *TopicFWMessage) String() string { return proto.CompactTextString(m) }
func (*TopicFWMessage) ProtoMessage()    {}
func (*TopicFWMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{9}
}

func (m *TopicFWMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicFWMessage.Unmarshal(m, b)
}
func (m *TopicFWMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicFWMessage.Marshal(b, m, deterministic)
}
func (m *TopicFWMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicFWMessage.Merge(m, src)
}
func (m *TopicFWMessage) XXX_Size() int {
	return xxx_messageInfo_TopicFWMessage.Size(m)
}
func (m *TopicFWMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicFWMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TopicFWMessage proto.InternalMessageInfo

func (m *TopicFWMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *TopicFWMessage) GetFromAlias() uint64 {
	if m != nil {
		return m.FromAlias
	}
	return 0
}

func (m *TopicFWMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type TopicIdentityMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	FromAlias            uint64      `protobuf:"varint,2,opt,name=from_alias,json=fromAlias,proto3" json:"from_alias,omitempty"`
	Topic                string      `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Identity             []byte      `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	Role                 Role        `protobuf:"varint,5,opt,name=role,proto3,enum=protocol.Role" json:"role,omitempty"`
	Body                 []byte      `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TopicIdentityMessage) Reset()         { *m = TopicIdentityMessage{} }
func (m *TopicIdentityMessage) String() string { return proto.CompactTextString(m) }
func (*TopicIdentityMessage) ProtoMessage()    {}
func (*TopicIdentityMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{10}
}

func (m *TopicIdentityMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicIdentityMessage.Unmarshal(m, b)
}
func (m *TopicIdentityMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicIdentityMessage.Marshal(b, m, deterministic)
}
func (m *TopicIdentityMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicIdentityMessage.Merge(m, src)
}
func (m *TopicIdentityMessage) XXX_Size() int {
	return xxx_messageInfo_TopicIdentityMessage.Size(m)
}
func (m *TopicIdentityMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicIdentityMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TopicIdentityMessage proto.InternalMessageInfo

func (m *TopicIdentityMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *TopicIdentityMessage) GetFromAlias() uint64 {
	if m != nil {
		return m.FromAlias
	}
	return 0
}

func (m *TopicIdentityMessage) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *TopicIdentityMessage) GetIdentity() []byte {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *TopicIdentityMessage) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_UNKNOWN_ROLE
}

func (m *TopicIdentityMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type TopicIdentityFWMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	FromAlias            uint64      `protobuf:"varint,2,opt,name=from_alias,json=fromAlias,proto3" json:"from_alias,omitempty"`
	Identity             []byte      `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	Role                 Role        `protobuf:"varint,4,opt,name=role,proto3,enum=protocol.Role" json:"role,omitempty"`
	Body                 []byte      `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TopicIdentityFWMessage) Reset()         { *m = TopicIdentityFWMessage{} }
func (m *TopicIdentityFWMessage) String() string { return proto.CompactTextString(m) }
func (*TopicIdentityFWMessage) ProtoMessage()    {}
func (*TopicIdentityFWMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{11}
}

func (m *TopicIdentityFWMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicIdentityFWMessage.Unmarshal(m, b)
}
func (m *TopicIdentityFWMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicIdentityFWMessage.Marshal(b, m, deterministic)
}
func (m *TopicIdentityFWMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicIdentityFWMessage.Merge(m, src)
}
func (m *TopicIdentityFWMessage) XXX_Size() int {
	return xxx_messageInfo_TopicIdentityFWMessage.Size(m)
}
func (m *TopicIdentityFWMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicIdentityFWMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TopicIdentityFWMessage proto.InternalMessageInfo

func (m *TopicIdentityFWMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *TopicIdentityFWMessage) GetFromAlias() uint64 {
	if m != nil {
		return m.FromAlias
	}
	return 0
}

func (m *TopicIdentityFWMessage) GetIdentity() []byte {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *TopicIdentityFWMessage) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_UNKNOWN_ROLE
}

func (m *TopicIdentityFWMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("protocol.Role", Role_name, Role_value)
	proto.RegisterEnum("protocol.Format", Format_name, Format_value)
	proto.RegisterType((*CoordinatorMessage)(nil), "protocol.CoordinatorMessage")
	proto.RegisterType((*WelcomeMessage)(nil), "protocol.WelcomeMessage")
	proto.RegisterType((*ConnectMessage)(nil), "protocol.ConnectMessage")
	proto.RegisterType((*WebRtcMessage)(nil), "protocol.WebRtcMessage")
	proto.RegisterType((*MessageHeader)(nil), "protocol.MessageHeader")
	proto.RegisterType((*PingMessage)(nil), "protocol.PingMessage")
	proto.RegisterType((*SubscriptionMessage)(nil), "protocol.SubscriptionMessage")
	proto.RegisterType((*AuthMessage)(nil), "protocol.AuthMessage")
	proto.RegisterType((*TopicMessage)(nil), "protocol.TopicMessage")
	proto.RegisterType((*TopicFWMessage)(nil), "protocol.TopicFWMessage")
	proto.RegisterType((*TopicIdentityMessage)(nil), "protocol.TopicIdentityMessage")
	proto.RegisterType((*TopicIdentityFWMessage)(nil), "protocol.TopicIdentityFWMessage")
}

func init() { proto.RegisterFile("broker.proto", fileDescriptor_f209535e190f2bed) }

var fileDescriptor_f209535e190f2bed = []byte{
	// 675 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0x63, 0x30, 0x04, 0x06, 0x82, 0x36, 0x5b, 0x12, 0xd1, 0x4a, 0x95, 0x90, 0x4f, 0x34,
	0x95, 0x22, 0x35, 0xbd, 0xf5, 0xd0, 0xca, 0x71, 0x96, 0xc4, 0x2a, 0xd8, 0x68, 0x6d, 0x6a, 0xa5,
	0x17, 0xcb, 0xc0, 0x26, 0xb5, 0x0a, 0xac, 0x65, 0x6f, 0x22, 0x71, 0xe9, 0xa1, 0x87, 0x3e, 0x52,
	0x1f, 0xa2, 0x8f, 0xd2, 0xa7, 0xa8, 0x76, 0x71, 0x08, 0x91, 0x5a, 0x29, 0x41, 0x69, 0x4e, 0xec,
	0xfc, 0x61, 0xbe, 0xdf, 0x37, 0x83, 0x80, 0xfa, 0x28, 0xe5, 0x5f, 0x59, 0x7a, 0x98, 0xa4, 0x5c,
	0x70, 0x5c, 0x51, 0x1f, 0x63, 0x3e, 0x35, 0x3e, 0x00, 0xb6, 0x38, 0x4f, 0x27, 0xf1, 0x3c, 0x12,
	0x3c, 0xed, 0xb3, 0x2c, 0x8b, 0x2e, 0x19, 0x7e, 0x05, 0xba, 0x58, 0x24, 0xac, 0xa5, 0xb5, 0xb5,
	0x4e, 0xe3, 0x68, 0xef, 0xf0, 0xa6, 0xfd, 0x30, 0x6f, 0xf0, 0x17, 0x09, 0xa3, 0xaa, 0xc5, 0xf8,
	0x06, 0x8d, 0x80, 0x4d, 0xc7, 0x7c, 0xc6, 0x1e, 0xfe, 0x65, 0xdc, 0x84, 0x52, 0x34, 0x8d, 0xa3,
	0xac, 0x55, 0x68, 0x6b, 0x1d, 0x9d, 0x2e, 0x03, 0xfc, 0x1a, 0x76, 0xa3, 0xeb, 0x28, 0x9e, 0x46,
	0xa3, 0x29, 0x0b, 0x33, 0x96, 0x5e, 0xb3, 0x34, 0x6b, 0x15, 0xdb, 0xc5, 0x8e, 0x4e, 0xd1, 0xaa,
	0xe0, 0x2d, 0xf3, 0xc6, 0x15, 0x34, 0x2c, 0x3e, 0x9f, 0xb3, 0xb1, 0xd8, 0x40, 0xff, 0x25, 0xc0,
	0x45, 0xca, 0x67, 0xe1, 0x3a, 0x44, 0x55, 0x66, 0x4c, 0x05, 0xf2, 0x1c, 0x2a, 0x82, 0xe7, 0xc5,
	0xa2, 0x2a, 0x6e, 0x0b, 0xae, 0x4a, 0xc6, 0x0f, 0x0d, 0x76, 0x02, 0x36, 0xa2, 0x62, 0xfc, 0x94,
	0xb2, 0x18, 0x41, 0x31, 0x9b, 0x24, 0x2d, 0xbd, 0xad, 0x75, 0xaa, 0x54, 0x3e, 0x8d, 0x77, 0xb0,
	0x93, 0x0b, 0x9c, 0xb1, 0x68, 0xc2, 0xd2, 0x87, 0xdc, 0xae, 0x07, 0xb5, 0x41, 0x3c, 0xbf, 0xdc,
	0xc0, 0x01, 0x06, 0x5d, 0xc4, 0x33, 0xa6, 0xd8, 0x35, 0xaa, 0xde, 0xc6, 0x77, 0x0d, 0x9e, 0x79,
	0x57, 0xa3, 0x6c, 0x9c, 0xc6, 0x89, 0x88, 0xf9, 0x7c, 0x83, 0xb1, 0x1d, 0x28, 0x5f, 0xf0, 0x74,
	0x16, 0x09, 0x35, 0xb8, 0x71, 0x84, 0x6e, 0x9b, 0xbb, 0x2a, 0x4f, 0xf3, 0x3a, 0xde, 0x87, 0xb2,
	0xe0, 0x49, 0x3c, 0x5e, 0x6e, 0xa8, 0x4e, 0xf3, 0xc8, 0x48, 0xa0, 0x66, 0x5e, 0x89, 0x2f, 0x1b,
	0x68, 0x1b, 0xa0, 0xa7, 0x7c, 0xca, 0x72, 0xe5, 0xc6, 0x6d, 0x2b, 0xe5, 0x53, 0x46, 0x55, 0x4d,
	0xda, 0x1e, 0xf1, 0xc9, 0x22, 0xd7, 0x54, 0x6f, 0x69, 0xbb, 0xee, 0x4b, 0xf1, 0xc7, 0xff, 0x21,
	0x34, 0xa1, 0xa4, 0x6c, 0x29, 0xbd, 0x2a, 0x5d, 0x06, 0x2b, 0x08, 0x7d, 0x0d, 0x62, 0x0e, 0x0d,
	0xc5, 0xd0, 0x0d, 0x1e, 0x9f, 0xe2, 0x6f, 0xa6, 0x7f, 0x69, 0xd0, 0x54, 0x82, 0xf6, 0x84, 0xcd,
	0x45, 0x2c, 0x16, 0x4f, 0x65, 0xfe, 0x05, 0x54, 0xe2, 0x5c, 0x32, 0x5f, 0xc0, 0x2a, 0x5e, 0x5d,
	0xb0, 0x74, 0x8f, 0x0b, 0x96, 0xd7, 0xcc, 0xfc, 0xd4, 0x60, 0xff, 0x8e, 0x99, 0xff, 0xb1, 0xc5,
	0x75, 0xf0, 0xe2, 0x3f, 0xc0, 0xf5, 0x7b, 0x80, 0x97, 0x6e, 0xc1, 0x0f, 0x7e, 0x6b, 0x50, 0x5b,
	0x03, 0xc1, 0x2d, 0x68, 0x0e, 0x9d, 0x8f, 0x8e, 0x1b, 0x38, 0x61, 0x9f, 0x78, 0x9e, 0x79, 0x4a,
	0x42, 0xff, 0x7c, 0x40, 0xd0, 0x16, 0xae, 0xc1, 0x76, 0x40, 0x7a, 0x96, 0xdb, 0x27, 0x48, 0x93,
	0x81, 0xe5, 0x3a, 0x0e, 0xb1, 0x7c, 0x54, 0xc0, 0x08, 0xea, 0x01, 0x39, 0xa6, 0xbe, 0x15, 0xba,
	0xdd, 0x2e, 0xa1, 0xa8, 0x88, 0x77, 0x61, 0x27, 0xcf, 0x98, 0x8e, 0x17, 0x10, 0x8a, 0x74, 0x39,
	0x38, 0x4f, 0xd9, 0x16, 0x09, 0x2d, 0xd3, 0x39, 0xb1, 0x4f, 0x4c, 0x9f, 0xa0, 0x12, 0xae, 0x80,
	0x3e, 0xb0, 0x9d, 0x53, 0x54, 0x96, 0x83, 0xbc, 0xe1, 0xb1, 0x67, 0x51, 0x7b, 0xe0, 0xdb, 0xae,
	0x83, 0xb6, 0x65, 0xcd, 0x1c, 0xfa, 0x67, 0xa8, 0x82, 0xab, 0x50, 0xf2, 0xdd, 0x81, 0x6d, 0xa1,
	0x2a, 0xae, 0x43, 0x45, 0x3d, 0xc3, 0x6e, 0x80, 0x00, 0x63, 0x68, 0x2c, 0x23, 0xfb, 0x84, 0x38,
	0xbe, 0xed, 0x9f, 0xa3, 0x1a, 0xde, 0x83, 0xdd, 0xbb, 0x39, 0xd9, 0x5a, 0x3f, 0x78, 0x0f, 0xba,
	0x5c, 0x87, 0xd4, 0xb9, 0x31, 0x49, 0xdd, 0x9e, 0x34, 0x07, 0x50, 0xb6, 0x7a, 0x36, 0x71, 0x7c,
	0xa4, 0x49, 0x52, 0xcb, 0xed, 0xf7, 0x87, 0x8e, 0x6d, 0x99, 0x12, 0x23, 0xf4, 0x08, 0xfd, 0x44,
	0x28, 0x2a, 0x1c, 0xbc, 0x81, 0xf2, 0xf2, 0x3f, 0x44, 0x8a, 0xde, 0x4c, 0xe8, 0xba, 0xb4, 0x6f,
	0xfa, 0x68, 0x4b, 0x12, 0x0e, 0x7a, 0xa6, 0xed, 0x20, 0x4d, 0x62, 0x9f, 0x7e, 0xb6, 0x07, 0xa8,
	0x30, 0x2a, 0xab, 0x43, 0xbc, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xa1, 0x49, 0x39, 0x3d,
	0x07, 0x00, 0x00,
}
