// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commproto.proto

package commproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_UNKNOWN_MESSAGE_TYPE MessageType = 0
	MessageType_WELCOME              MessageType = 1
	MessageType_CONNECT              MessageType = 2
	MessageType_WEBRTC_SUPPORTED     MessageType = 3
	MessageType_WEBRTC_OFFER         MessageType = 4
	MessageType_WEBRTC_ANSWER        MessageType = 5
	MessageType_WEBRTC_ICE_CANDIDATE MessageType = 6
	MessageType_PING                 MessageType = 7
	MessageType_TOPIC_SUBSCRIPTION   MessageType = 8
	MessageType_TOPIC                MessageType = 9
	MessageType_AUTH                 MessageType = 10
)

var MessageType_name = map[int32]string{
	0:  "UNKNOWN_MESSAGE_TYPE",
	1:  "WELCOME",
	2:  "CONNECT",
	3:  "WEBRTC_SUPPORTED",
	4:  "WEBRTC_OFFER",
	5:  "WEBRTC_ANSWER",
	6:  "WEBRTC_ICE_CANDIDATE",
	7:  "PING",
	8:  "TOPIC_SUBSCRIPTION",
	9:  "TOPIC",
	10: "AUTH",
}

var MessageType_value = map[string]int32{
	"UNKNOWN_MESSAGE_TYPE": 0,
	"WELCOME":              1,
	"CONNECT":              2,
	"WEBRTC_SUPPORTED":     3,
	"WEBRTC_OFFER":         4,
	"WEBRTC_ANSWER":        5,
	"WEBRTC_ICE_CANDIDATE": 6,
	"PING":                 7,
	"TOPIC_SUBSCRIPTION":   8,
	"TOPIC":                9,
	"AUTH":                 10,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{0}
}

type Role int32

const (
	Role_UNKNOWN_ROLE         Role = 0
	Role_CLIENT               Role = 1
	Role_COMMUNICATION_SERVER Role = 2
)

var Role_name = map[int32]string{
	0: "UNKNOWN_ROLE",
	1: "CLIENT",
	2: "COMMUNICATION_SERVER",
}

var Role_value = map[string]int32{
	"UNKNOWN_ROLE":         0,
	"CLIENT":               1,
	"COMMUNICATION_SERVER": 2,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{1}
}

type Format int32

const (
	Format_UNKNOWN_FORMAT Format = 0
	Format_PLAIN          Format = 1
	Format_GZIP           Format = 2
)

var Format_name = map[int32]string{
	0: "UNKNOWN_FORMAT",
	1: "PLAIN",
	2: "GZIP",
}

var Format_value = map[string]int32{
	"UNKNOWN_FORMAT": 0,
	"PLAIN":          1,
	"GZIP":           2,
}

func (x Format) String() string {
	return proto.EnumName(Format_name, int32(x))
}

func (Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{2}
}

type CoordinatorMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CoordinatorMessage) Reset()         { *m = CoordinatorMessage{} }
func (m *CoordinatorMessage) String() string { return proto.CompactTextString(m) }
func (*CoordinatorMessage) ProtoMessage()    {}
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{0}
}

func (m *CoordinatorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoordinatorMessage.Unmarshal(m, b)
}
func (m *CoordinatorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoordinatorMessage.Marshal(b, m, deterministic)
}
func (m *CoordinatorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoordinatorMessage.Merge(m, src)
}
func (m *CoordinatorMessage) XXX_Size() int {
	return xxx_messageInfo_CoordinatorMessage.Size(m)
}
func (m *CoordinatorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CoordinatorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CoordinatorMessage proto.InternalMessageInfo

func (m *CoordinatorMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

type WelcomeMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Alias                string      `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	AvailableServers     []string    `protobuf:"bytes,3,rep,name=available_servers,json=availableServers,proto3" json:"available_servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WelcomeMessage) Reset()         { *m = WelcomeMessage{} }
func (m *WelcomeMessage) String() string { return proto.CompactTextString(m) }
func (*WelcomeMessage) ProtoMessage()    {}
func (*WelcomeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{1}
}

func (m *WelcomeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WelcomeMessage.Unmarshal(m, b)
}
func (m *WelcomeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WelcomeMessage.Marshal(b, m, deterministic)
}
func (m *WelcomeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WelcomeMessage.Merge(m, src)
}
func (m *WelcomeMessage) XXX_Size() int {
	return xxx_messageInfo_WelcomeMessage.Size(m)
}
func (m *WelcomeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WelcomeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WelcomeMessage proto.InternalMessageInfo

func (m *WelcomeMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *WelcomeMessage) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *WelcomeMessage) GetAvailableServers() []string {
	if m != nil {
		return m.AvailableServers
	}
	return nil
}

type ConnectMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	FromAlias            string      `protobuf:"bytes,2,opt,name=from_alias,json=fromAlias,proto3" json:"from_alias,omitempty"`
	ToAlias              string      `protobuf:"bytes,3,opt,name=to_alias,json=toAlias,proto3" json:"to_alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConnectMessage) Reset()         { *m = ConnectMessage{} }
func (m *ConnectMessage) String() string { return proto.CompactTextString(m) }
func (*ConnectMessage) ProtoMessage()    {}
func (*ConnectMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{2}
}

func (m *ConnectMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectMessage.Unmarshal(m, b)
}
func (m *ConnectMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectMessage.Marshal(b, m, deterministic)
}
func (m *ConnectMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectMessage.Merge(m, src)
}
func (m *ConnectMessage) XXX_Size() int {
	return xxx_messageInfo_ConnectMessage.Size(m)
}
func (m *ConnectMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectMessage proto.InternalMessageInfo

func (m *ConnectMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *ConnectMessage) GetFromAlias() string {
	if m != nil {
		return m.FromAlias
	}
	return ""
}

func (m *ConnectMessage) GetToAlias() string {
	if m != nil {
		return m.ToAlias
	}
	return ""
}

type WebRtcMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	FromAlias            string      `protobuf:"bytes,2,opt,name=from_alias,json=fromAlias,proto3" json:"from_alias,omitempty"`
	ToAlias              string      `protobuf:"bytes,3,opt,name=to_alias,json=toAlias,proto3" json:"to_alias,omitempty"`
	Sdp                  string      `protobuf:"bytes,4,opt,name=sdp,proto3" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WebRtcMessage) Reset()         { *m = WebRtcMessage{} }
func (m *WebRtcMessage) String() string { return proto.CompactTextString(m) }
func (*WebRtcMessage) ProtoMessage()    {}
func (*WebRtcMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{3}
}

func (m *WebRtcMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebRtcMessage.Unmarshal(m, b)
}
func (m *WebRtcMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebRtcMessage.Marshal(b, m, deterministic)
}
func (m *WebRtcMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebRtcMessage.Merge(m, src)
}
func (m *WebRtcMessage) XXX_Size() int {
	return xxx_messageInfo_WebRtcMessage.Size(m)
}
func (m *WebRtcMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WebRtcMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WebRtcMessage proto.InternalMessageInfo

func (m *WebRtcMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *WebRtcMessage) GetFromAlias() string {
	if m != nil {
		return m.FromAlias
	}
	return ""
}

func (m *WebRtcMessage) GetToAlias() string {
	if m != nil {
		return m.ToAlias
	}
	return ""
}

func (m *WebRtcMessage) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

type WorldCommMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WorldCommMessage) Reset()         { *m = WorldCommMessage{} }
func (m *WorldCommMessage) String() string { return proto.CompactTextString(m) }
func (*WorldCommMessage) ProtoMessage()    {}
func (*WorldCommMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{4}
}

func (m *WorldCommMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldCommMessage.Unmarshal(m, b)
}
func (m *WorldCommMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldCommMessage.Marshal(b, m, deterministic)
}
func (m *WorldCommMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldCommMessage.Merge(m, src)
}
func (m *WorldCommMessage) XXX_Size() int {
	return xxx_messageInfo_WorldCommMessage.Size(m)
}
func (m *WorldCommMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldCommMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WorldCommMessage proto.InternalMessageInfo

func (m *WorldCommMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

type PingMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Time                 float64     `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{5}
}

func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (m *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(m, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *PingMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// NOTE: topics is a space separated string in the format specified by Format
type TopicSubscriptionMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Format               Format      `protobuf:"varint,2,opt,name=format,proto3,enum=Format" json:"format,omitempty"`
	Topics               []byte      `protobuf:"bytes,3,opt,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TopicSubscriptionMessage) Reset()         { *m = TopicSubscriptionMessage{} }
func (m *TopicSubscriptionMessage) String() string { return proto.CompactTextString(m) }
func (*TopicSubscriptionMessage) ProtoMessage()    {}
func (*TopicSubscriptionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{6}
}

func (m *TopicSubscriptionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicSubscriptionMessage.Unmarshal(m, b)
}
func (m *TopicSubscriptionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicSubscriptionMessage.Marshal(b, m, deterministic)
}
func (m *TopicSubscriptionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicSubscriptionMessage.Merge(m, src)
}
func (m *TopicSubscriptionMessage) XXX_Size() int {
	return xxx_messageInfo_TopicSubscriptionMessage.Size(m)
}
func (m *TopicSubscriptionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicSubscriptionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TopicSubscriptionMessage proto.InternalMessageInfo

func (m *TopicSubscriptionMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *TopicSubscriptionMessage) GetFormat() Format {
	if m != nil {
		return m.Format
	}
	return Format_UNKNOWN_FORMAT
}

func (m *TopicSubscriptionMessage) GetTopics() []byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

type TopicMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Topic                string      `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	FromAlias            string      `protobuf:"bytes,4,opt,name=from_alias,json=fromAlias,proto3" json:"from_alias,omitempty"`
	Body                 []byte      `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TopicMessage) Reset()         { *m = TopicMessage{} }
func (m *TopicMessage) String() string { return proto.CompactTextString(m) }
func (*TopicMessage) ProtoMessage()    {}
func (*TopicMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{7}
}

func (m *TopicMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicMessage.Unmarshal(m, b)
}
func (m *TopicMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicMessage.Marshal(b, m, deterministic)
}
func (m *TopicMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicMessage.Merge(m, src)
}
func (m *TopicMessage) XXX_Size() int {
	return xxx_messageInfo_TopicMessage.Size(m)
}
func (m *TopicMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TopicMessage proto.InternalMessageInfo

func (m *TopicMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *TopicMessage) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *TopicMessage) GetFromAlias() string {
	if m != nil {
		return m.FromAlias
	}
	return ""
}

func (m *TopicMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type AuthMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Role                 Role        `protobuf:"varint,2,opt,name=role,proto3,enum=Role" json:"role,omitempty"`
	Method               string      `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Body                 []byte      `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AuthMessage) Reset()         { *m = AuthMessage{} }
func (m *AuthMessage) String() string { return proto.CompactTextString(m) }
func (*AuthMessage) ProtoMessage()    {}
func (*AuthMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{8}
}

func (m *AuthMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMessage.Unmarshal(m, b)
}
func (m *AuthMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMessage.Marshal(b, m, deterministic)
}
func (m *AuthMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMessage.Merge(m, src)
}
func (m *AuthMessage) XXX_Size() int {
	return xxx_messageInfo_AuthMessage.Size(m)
}
func (m *AuthMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMessage proto.InternalMessageInfo

func (m *AuthMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *AuthMessage) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_UNKNOWN_ROLE
}

func (m *AuthMessage) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *AuthMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type PositionData struct {
	Time                 float64  `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	PositionX            float32  `protobuf:"fixed32,2,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY            float32  `protobuf:"fixed32,3,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	PositionZ            float32  `protobuf:"fixed32,4,opt,name=position_z,json=positionZ,proto3" json:"position_z,omitempty"`
	RotationX            float32  `protobuf:"fixed32,5,opt,name=rotation_x,json=rotationX,proto3" json:"rotation_x,omitempty"`
	RotationY            float32  `protobuf:"fixed32,6,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
	RotationZ            float32  `protobuf:"fixed32,7,opt,name=rotation_z,json=rotationZ,proto3" json:"rotation_z,omitempty"`
	RotationW            float32  `protobuf:"fixed32,8,opt,name=rotation_w,json=rotationW,proto3" json:"rotation_w,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionData) Reset()         { *m = PositionData{} }
func (m *PositionData) String() string { return proto.CompactTextString(m) }
func (*PositionData) ProtoMessage()    {}
func (*PositionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{9}
}

func (m *PositionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionData.Unmarshal(m, b)
}
func (m *PositionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionData.Marshal(b, m, deterministic)
}
func (m *PositionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionData.Merge(m, src)
}
func (m *PositionData) XXX_Size() int {
	return xxx_messageInfo_PositionData.Size(m)
}
func (m *PositionData) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionData.DiscardUnknown(m)
}

var xxx_messageInfo_PositionData proto.InternalMessageInfo

func (m *PositionData) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PositionData) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *PositionData) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

func (m *PositionData) GetPositionZ() float32 {
	if m != nil {
		return m.PositionZ
	}
	return 0
}

func (m *PositionData) GetRotationX() float32 {
	if m != nil {
		return m.RotationX
	}
	return 0
}

func (m *PositionData) GetRotationY() float32 {
	if m != nil {
		return m.RotationY
	}
	return 0
}

func (m *PositionData) GetRotationZ() float32 {
	if m != nil {
		return m.RotationZ
	}
	return 0
}

func (m *PositionData) GetRotationW() float32 {
	if m != nil {
		return m.RotationW
	}
	return 0
}

type ProfileData struct {
	Time                 float64  `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	AvatarType           string   `protobuf:"bytes,2,opt,name=avatar_type,json=avatarType,proto3" json:"avatar_type,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PublicKey            string   `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileData) Reset()         { *m = ProfileData{} }
func (m *ProfileData) String() string { return proto.CompactTextString(m) }
func (*ProfileData) ProtoMessage()    {}
func (*ProfileData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{10}
}

func (m *ProfileData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileData.Unmarshal(m, b)
}
func (m *ProfileData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileData.Marshal(b, m, deterministic)
}
func (m *ProfileData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileData.Merge(m, src)
}
func (m *ProfileData) XXX_Size() int {
	return xxx_messageInfo_ProfileData.Size(m)
}
func (m *ProfileData) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileData.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileData proto.InternalMessageInfo

func (m *ProfileData) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ProfileData) GetAvatarType() string {
	if m != nil {
		return m.AvatarType
	}
	return ""
}

func (m *ProfileData) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ProfileData) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type ChatData struct {
	Time                 float64  `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	MessageId            string   `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatData) Reset()         { *m = ChatData{} }
func (m *ChatData) String() string { return proto.CompactTextString(m) }
func (*ChatData) ProtoMessage()    {}
func (*ChatData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f0b7582b0652215, []int{11}
}

func (m *ChatData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatData.Unmarshal(m, b)
}
func (m *ChatData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatData.Marshal(b, m, deterministic)
}
func (m *ChatData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatData.Merge(m, src)
}
func (m *ChatData) XXX_Size() int {
	return xxx_messageInfo_ChatData.Size(m)
}
func (m *ChatData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatData.DiscardUnknown(m)
}

var xxx_messageInfo_ChatData proto.InternalMessageInfo

func (m *ChatData) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ChatData) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *ChatData) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterEnum("MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("Role", Role_name, Role_value)
	proto.RegisterEnum("Format", Format_name, Format_value)
	proto.RegisterType((*CoordinatorMessage)(nil), "CoordinatorMessage")
	proto.RegisterType((*WelcomeMessage)(nil), "WelcomeMessage")
	proto.RegisterType((*ConnectMessage)(nil), "ConnectMessage")
	proto.RegisterType((*WebRtcMessage)(nil), "WebRtcMessage")
	proto.RegisterType((*WorldCommMessage)(nil), "WorldCommMessage")
	proto.RegisterType((*PingMessage)(nil), "PingMessage")
	proto.RegisterType((*TopicSubscriptionMessage)(nil), "TopicSubscriptionMessage")
	proto.RegisterType((*TopicMessage)(nil), "TopicMessage")
	proto.RegisterType((*AuthMessage)(nil), "AuthMessage")
	proto.RegisterType((*PositionData)(nil), "PositionData")
	proto.RegisterType((*ProfileData)(nil), "ProfileData")
	proto.RegisterType((*ChatData)(nil), "ChatData")
}

func init() { proto.RegisterFile("commproto.proto", fileDescriptor_6f0b7582b0652215) }

var fileDescriptor_6f0b7582b0652215 = []byte{
	// 768 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0xcf, 0x6f, 0xdb, 0x36,
	0x14, 0xc7, 0x2b, 0x5b, 0xfe, 0xf5, 0xec, 0x7a, 0x2c, 0x11, 0x14, 0xea, 0x61, 0x68, 0xa6, 0x53,
	0x90, 0x01, 0x01, 0xd6, 0x0d, 0x3b, 0x0e, 0x50, 0x15, 0x25, 0x13, 0x1a, 0x4b, 0x1a, 0xad, 0xcc,
	0x4d, 0x2f, 0x02, 0x6d, 0x33, 0x8d, 0x30, 0xc9, 0x14, 0x24, 0xda, 0xab, 0x0a, 0xec, 0xb6, 0x7f,
	0x6f, 0x7f, 0xd1, 0x2e, 0x03, 0x29, 0x3a, 0xb3, 0x02, 0x6c, 0xf0, 0x2e, 0xbb, 0x04, 0x7c, 0xdf,
	0xaf, 0xf4, 0x3e, 0x7c, 0x3f, 0x14, 0xc3, 0x17, 0x2b, 0x9e, 0xe7, 0x45, 0xc9, 0x05, 0xbf, 0x50,
	0x7f, 0xed, 0xef, 0x01, 0xbb, 0x9c, 0x97, 0xeb, 0x74, 0x43, 0x05, 0x2f, 0x67, 0xac, 0xaa, 0xe8,
	0x47, 0x86, 0x4f, 0xc1, 0x14, 0x75, 0xc1, 0x2c, 0xe3, 0xd4, 0x38, 0x9b, 0xbe, 0x99, 0x5c, 0x68,
	0x3d, 0xae, 0x0b, 0x46, 0x94, 0x63, 0x6f, 0x61, 0xba, 0x60, 0xd9, 0x8a, 0xe7, 0xec, 0xe8, 0x77,
	0xf0, 0x09, 0xf4, 0x68, 0x96, 0xd2, 0xca, 0xea, 0x9c, 0x1a, 0x67, 0x23, 0xd2, 0x04, 0xf8, 0x6b,
	0x78, 0x41, 0x77, 0x34, 0xcd, 0xe8, 0x32, 0x63, 0x49, 0xc5, 0xca, 0x1d, 0x2b, 0x2b, 0xab, 0x7b,
	0xda, 0x3d, 0x1b, 0x11, 0xf4, 0x68, 0xcc, 0x1b, 0xdd, 0xce, 0x60, 0xea, 0xf2, 0xcd, 0x86, 0xad,
	0xc4, 0xf1, 0xd8, 0x2f, 0x01, 0xee, 0x4b, 0x9e, 0x27, 0x87, 0xec, 0x91, 0x54, 0x1c, 0xc5, 0x7f,
	0x05, 0x43, 0xc1, 0xb5, 0xd9, 0x55, 0xe6, 0x40, 0x70, 0x65, 0xd9, 0xbf, 0xc1, 0xf3, 0x05, 0x5b,
	0x12, 0xb1, 0xfa, 0x1f, 0x60, 0x18, 0x41, 0xb7, 0x5a, 0x17, 0x96, 0xa9, 0x54, 0x79, 0xb4, 0xbf,
	0x03, 0xb4, 0xe0, 0x65, 0xb6, 0x76, 0x79, 0x9e, 0x1f, 0x3f, 0x19, 0x17, 0xc6, 0x51, 0xba, 0xf9,
	0x78, 0xfc, 0x95, 0x31, 0x98, 0x22, 0xcd, 0x99, 0xba, 0xac, 0x41, 0xd4, 0xd9, 0xde, 0x82, 0x15,
	0xf3, 0x22, 0x5d, 0xcd, 0xb7, 0xcb, 0x6a, 0x55, 0xa6, 0x85, 0x48, 0xf9, 0xe6, 0xf8, 0x8c, 0xaf,
	0xa1, 0x7f, 0xcf, 0xcb, 0x9c, 0x0a, 0x95, 0x73, 0xfa, 0x66, 0x70, 0x71, 0xa5, 0x42, 0xa2, 0x65,
	0xfc, 0x12, 0xfa, 0x42, 0xa6, 0x6f, 0x9a, 0x30, 0x21, 0x3a, 0xb2, 0x6b, 0x98, 0x28, 0xec, 0x7f,
	0xda, 0x29, 0xf5, 0xae, 0xee, 0x66, 0x13, 0x3c, 0x99, 0x82, 0xf9, 0x74, 0x0a, 0x18, 0xcc, 0x25,
	0x5f, 0xd7, 0x56, 0x4f, 0xc1, 0xd5, 0xd9, 0xde, 0xc1, 0xd8, 0xd9, 0x8a, 0x87, 0xe3, 0xc9, 0xaf,
	0xc0, 0x2c, 0x79, 0xc6, 0x74, 0x89, 0xbd, 0x0b, 0xc2, 0x33, 0x46, 0x94, 0x24, 0xcb, 0xcb, 0x99,
	0x78, 0xe0, 0x6b, 0x7d, 0x2b, 0x1d, 0x3d, 0x72, 0xcd, 0x03, 0xee, 0x9f, 0x06, 0x4c, 0x22, 0x5e,
	0xa5, 0xb2, 0xc3, 0x97, 0x54, 0xd0, 0xc7, 0x71, 0x18, 0x7f, 0x8f, 0x43, 0xd6, 0x53, 0xe8, 0x67,
	0x92, 0x4f, 0x8a, 0xd8, 0x21, 0xa3, 0xbd, 0xf2, 0xbe, 0x65, 0xd7, 0x8a, 0x79, 0x60, 0xdf, 0xb5,
	0xec, 0xcf, 0x0a, 0x7e, 0x60, 0x7f, 0x90, 0x76, 0xc9, 0x05, 0xd5, 0xc9, 0x7b, 0x8d, 0xbd, 0x57,
	0xde, 0xb7, 0xec, 0xda, 0xea, 0xb7, 0xed, 0xbb, 0x96, 0xfd, 0xd9, 0x1a, 0xb4, 0xed, 0x76, 0xf2,
	0x5f, 0xad, 0x61, 0xdb, 0x5e, 0xd8, 0xbf, 0x1b, 0x30, 0x8e, 0x4a, 0x7e, 0x9f, 0x66, 0xec, 0x1f,
	0x8b, 0x7f, 0x0d, 0x63, 0xba, 0xa3, 0x82, 0x96, 0x89, 0x9a, 0x48, 0xf3, 0x4d, 0x41, 0x23, 0xc9,
	0x79, 0xe0, 0xaf, 0x60, 0xb2, 0x4e, 0xab, 0x22, 0xa3, 0x75, 0xb2, 0xa1, 0x39, 0xd3, 0x4d, 0x1f,
	0x6b, 0x2d, 0xa0, 0xba, 0x81, 0xdb, 0x65, 0x96, 0xae, 0x92, 0x5f, 0x58, 0xbd, 0x5f, 0x88, 0x46,
	0x79, 0xc7, 0x6a, 0xfb, 0x27, 0x18, 0xba, 0x0f, 0x54, 0xfc, 0x5b, 0xff, 0xf3, 0x66, 0x01, 0x92,
	0x74, 0xbd, 0xff, 0xaa, 0xb5, 0xe2, 0xab, 0xb9, 0x0a, 0xf6, 0x49, 0x68, 0xb0, 0x3a, 0x9f, 0xff,
	0x61, 0xc0, 0xf8, 0x60, 0x69, 0xb0, 0x05, 0x27, 0xb7, 0xc1, 0xbb, 0x20, 0x5c, 0x04, 0xc9, 0xcc,
	0x9b, 0xcf, 0x9d, 0x6b, 0x2f, 0x89, 0xef, 0x22, 0x0f, 0x3d, 0xc3, 0x63, 0x18, 0x2c, 0xbc, 0x1b,
	0x37, 0x9c, 0x79, 0xc8, 0x90, 0x81, 0x1b, 0x06, 0x81, 0xe7, 0xc6, 0xa8, 0x83, 0x4f, 0x00, 0x2d,
	0xbc, 0xb7, 0x24, 0x76, 0x93, 0xf9, 0x6d, 0x14, 0x85, 0x24, 0xf6, 0x2e, 0x51, 0x17, 0x23, 0x98,
	0x68, 0x35, 0xbc, 0xba, 0xf2, 0x08, 0x32, 0xf1, 0x0b, 0x78, 0xae, 0x15, 0x27, 0x98, 0x2f, 0x3c,
	0x82, 0x7a, 0x12, 0xa7, 0x25, 0xdf, 0xf5, 0x12, 0xd7, 0x09, 0x2e, 0xfd, 0x4b, 0x27, 0xf6, 0x50,
	0x1f, 0x0f, 0xc1, 0x8c, 0xfc, 0xe0, 0x1a, 0x0d, 0xf0, 0x4b, 0xc0, 0x71, 0x18, 0xf9, 0x32, 0xfb,
	0xdb, 0xb9, 0x4b, 0xfc, 0x28, 0xf6, 0xc3, 0x00, 0x0d, 0xf1, 0x08, 0x7a, 0x4a, 0x47, 0x23, 0xf9,
	0xb0, 0x73, 0x1b, 0xff, 0x88, 0xe0, 0xfc, 0x07, 0x30, 0xe5, 0x86, 0x4b, 0xfa, 0xbe, 0x0e, 0x12,
	0xde, 0xc8, 0xfb, 0x03, 0xf4, 0xdd, 0x1b, 0xdf, 0x0b, 0x62, 0x64, 0x48, 0xac, 0x1b, 0xce, 0x66,
	0xb7, 0x81, 0xef, 0x3a, 0x32, 0x5b, 0x32, 0xf7, 0xc8, 0xcf, 0x1e, 0x41, 0x9d, 0xf3, 0x6f, 0xa0,
	0xdf, 0xfc, 0x13, 0xc0, 0x18, 0xa6, 0xfb, 0x0c, 0x57, 0x21, 0x99, 0x39, 0x31, 0x7a, 0x26, 0x91,
	0xd1, 0x8d, 0xe3, 0x07, 0xc8, 0x90, 0xc8, 0xeb, 0x0f, 0x7e, 0x84, 0x3a, 0xcb, 0xbe, 0xfa, 0x89,
	0xfa, 0xf6, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x9d, 0xf1, 0x3f, 0xb5, 0x06, 0x00, 0x00,
}
